README.rst
* Update links into the readme.
Co-Authored-by: Lauren-D <laurent.dubois@uclouvain.be>
=> doc: update readme

CHANGES.rst, invenio_sip2/version.py
Co-Authored-by: Lauren-D <laurent.dubois@uclouvain.be>
=> release: v0.2.0

CHANGES.rst, invenio_sip2/version.py
=> release: v0.3.0

README.rst, invenio_sip2/actions/actions.py, invenio_sip2/actions/base.py, invenio_sip2/ext.py, invenio_sip2/handlers/api_handlers.py, invenio_sip2/handlers/base.py, invenio_sip2/helpers.py, invenio_sip2/models.py, tests/conftest.py, tests/test_actions.py, tests/test_helpers.py, tests/test_models.py, tests/test_server.py, tests/test_utils.py
* Writes more tests.
* remove useless methods.
Co-Authored-by: Lauren-D <laurent.dubois@uclouvain.be>
=> global: increase code coverage

invenio_sip2/actions/actions.py, invenio_sip2/actions/base.py, invenio_sip2/config.py, invenio_sip2/ext.py, invenio_sip2/handlers/__init__.py, invenio_sip2/handlers/api_handlers.py, invenio_sip2/handlers/base.py, invenio_sip2/models.py, tests/conftest.py, tests/fixtures/messages.py, tests/test_actions.py, tests/test_models.py, tests/utils.py
* Adds patron status external handler.
* Adapts patron status action.
=> action: implements patron status

CHANGES.rst, invenio_sip2/version.py
=> release: v0.4.0

.github/workflows/continuous-integration-test.yml, invenio_sip2/actions/actions.py, invenio_sip2/api.py, invenio_sip2/api_views.py, invenio_sip2/cli.py, invenio_sip2/config.py, invenio_sip2/datastore.py, invenio_sip2/errors.py, invenio_sip2/ext.py, invenio_sip2/records/__init__.py, invenio_sip2/records/record.py, invenio_sip2/server.py, invenio_sip2/templates/invenio_sip2/monitoring.html, invenio_sip2/utils.py, invenio_sip2/views.py, setup.py, tests/conftest.py, tests/fixtures/servers.py, tests/test_actions.py, tests/test_cli.py, tests/test_datastore.py, tests/test_server.py
* Adds datastore to save launched servers and connected clients.
* Adds record metadata management.
* Adds API for monitoring.
* Adapts tests.
=> monitoring: servers and clients

.github/workflows/continuous-integration-test.yml, invenio_sip2/actions/actions.py, invenio_sip2/actions/base.py, invenio_sip2/api_views.py, invenio_sip2/cli.py, invenio_sip2/config.py, invenio_sip2/decorators.py, invenio_sip2/errors.py, invenio_sip2/ext.py, invenio_sip2/handlers/base.py, invenio_sip2/models.py, invenio_sip2/permissions.py, invenio_sip2/records/record.py, invenio_sip2/server.py, invenio_sip2/views.py, setup.py, tests/conftest.py, tests/fixtures/servers.py, tests/test_actions.py, tests/utils.py
* Adds invenio-sip2 logger.
* Adds console logging configuration.
* Adds file system logging configuration.
* Uses new logger for logging.
* Adds a check when trying to start a new server.
* Adds permissions factory.
=> logging: implement invenio-sip2 logger

CHANGES.rst, invenio_sip2/version.py
=> project: release v0.5.0

CHANGES.rst, invenio_sip2/version.py
=> release: v5.0.1

.github/workflows/continuous-integration-test.yml, CHANGES.rst, CONTRIBUTING.rst, docs/api.rst, docs/conf.py, docs/usage.rst, examples/app.py, invenio_sip2/actions/actions.py, invenio_sip2/actions/base.py, invenio_sip2/handlers/api_handlers.py, invenio_sip2/handlers/base.py, invenio_sip2/records/record.py, invenio_sip2/utils.py, invenio_sip2/version.py, invenio_sip2/views/__init__.py, invenio_sip2/views/rest.py, invenio_sip2/views/views.py, setup.py, tests/conftest.py, tests/test_actions.py, tests/test_views_rest.py, tests/utils.py
=> global: coverage and refactoring

invenio_sip2/actions/actions.py, invenio_sip2/api.py, invenio_sip2/cli.py, invenio_sip2/config.py, invenio_sip2/records/record.py, invenio_sip2/server.py, setup.py
When the selcheck client send a request resend message, the sytem 
must return the last response sent.
* Adds sequence number error detection.
=> action: implement request resend action.

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.0

invenio_sip2/server.py
=> server: use invenio-sip2 logger

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.1

invenio_sip2/actions/actions.py, invenio_sip2/api.py, invenio_sip2/models.py, invenio_sip2/server.py
* Adds patron summary.
* Fixes fixed field wrong length.
=> action: implement summary for patron information

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.2

invenio_sip2/actions/actions.py, invenio_sip2/models.py
=> action: fix renew error

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.3

invenio_sip2/actions/actions.py, invenio_sip2/actions/base.py, invenio_sip2/api.py, invenio_sip2/cli.py, invenio_sip2/config.py, invenio_sip2/models.py, invenio_sip2/utils.py, tests/utils.py
* Fixes wrong circulation messages response.
* Fixes no such process in command line utilities.
=> actions: fix circulation messages response

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.4

invenio_sip2/actions/actions.py, invenio_sip2/ext.py, invenio_sip2/proxies.py, invenio_sip2/server.py
=> logging: adds debug information

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.5

CHANGES.rst, invenio_sip2/actions/actions.py, invenio_sip2/ext.py, invenio_sip2/proxies.py, invenio_sip2/server.py, invenio_sip2/version.py
=> merge dev to master

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.6

invenio_sip2/actions/actions.py, invenio_sip2/config.py, invenio_sip2/records/record.py, invenio_sip2/utils.py, tests/utils.py
* Fixes missing conversion of i18n language.
* Fixes date format.
=> actions: fix conversion language

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.7

invenio_sip2/server.py
=> server: catch runtime error

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.8

setup.py
* Fixes `invenio-search` version.
* Fixes `invenio-db` version.
Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
=> install: fix invenio versions

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.9

CHANGES.rst, invenio_sip2/version.py
=> release: v0.6.10

CHANGES.rst, invenio_sip2/api.py, invenio_sip2/utils.py, invenio_sip2/version.py, tests/test_actions.py
* Forces text encoding on checksum generation
=> release: v0.6.11

CHANGES.rst, invenio_sip2/ext.py, invenio_sip2/utils.py, invenio_sip2/version.py
* Fix missing parsing date.
* Adds module version in logging formatter.
=> release: v0.6.12

.gitignore, CHANGES.rst, README.rst, docs/conf.py, invenio_sip2/actions/actions.py, invenio_sip2/api.py, invenio_sip2/config.py, invenio_sip2/errors.py, invenio_sip2/records/record.py, invenio_sip2/server.py, invenio_sip2/views/rest.py, poetry.lock, pyproject.toml, setup.cfg, setup.py
* Changes logging level for `CommandNotFound` and `UnicodeDecodeError`.
* Cleans and beautifies some code.
* Restores setup.py.
* Updates setup configuration.
=> global: better code

invenio_sip2/actions/actions.py, invenio_sip2/api.py, invenio_sip2/errors.py, invenio_sip2/models.py, tests/conftest.py, tests/fixtures/messages.py, tests/test_actions.py, tests/test_messages_api.py, tests/test_views_rest.py, tests/utils.py
=> global: increase coverage

CHANGES.rst, invenio_sip2/version.py, pyproject.toml
=> release: v0.6.14

docs/conf.py, invenio_sip2/records/record.py, setup.cfg
=> dependencies: fix sphynx version

invenio_sip2/views/rest.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/test_views_rest.py, tests/utils.py
* Uses http method on monitoring api blueprint.
* Updates Flask dependency.
* Adapts some tests.
=> monitoring: set http method for blueprint

invenio_sip2/models.py
=> actions: fix missing hold items field in patron information response

invenio_sip2/actions/actions.py, invenio_sip2/config.py, invenio_sip2/errors.py, invenio_sip2/ext.py, invenio_sip2/handlers/__init__.py, invenio_sip2/handlers/api_handlers.py, invenio_sip2/handlers/base.py, invenio_sip2/helpers.py, invenio_sip2/models.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/fixtures/messages.py, tests/test_actions.py, tests/utils.py
This action is used to notify the ACS that a fee has been collected from the patron.
=> action: implement fee paid

poetry.lock
=> project: update dependencies
